#stages:
#  - build
#  - deploy
#
#build_backend:
#  stage: build
#  script:
#    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin
#    - docker build -t riper3d/docere_backend:$CI_COMMIT_SHA .
#    - docker tag riper3d/docere_backend:$CI_COMMIT_SHA riper3d/docere_backend:latest
#    - docker push riper3d/docere_backend:$CI_COMMIT_SHA
#    - docker push riper3d/docere_backend:latest
#
#build_frontend:
#  stage: build
#  before_script:
#    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin
#    - |
#    - cat > frontend/.env <<EOF
#    - VITE_API_BASE_URL=https://docere.online/api/
#    - EOF
#  script:
#    - docker build -t riper3d/docere_frontend:$CI_COMMIT_SHA ./frontend
#    - docker tag riper3d/docere_frontend:$CI_COMMIT_SHA riper3d/docere_frontend:latest
#    - docker push riper3d/docere_frontend:$CI_COMMIT_SHA
#    - docker push riper3d/docere_frontend:latest
#
#deploy:
#  stage: deploy
#  script:
#    - ssh $PROD_USER@$PROD_HOST '
#      cd ~/django_project &&
#      docker-compose pull &&
#      docker-compose down &&
#      docker volume rm django_project_react_build || true &&
#      docker-compose up -d --build
#      '
